DMSapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [

	path('show_delete_popup/<int:file_id>/', views.show_delete_popup, name='show_delete_popup'),
    path('download/file/<int:id>/<type>/', views.download_protection, name='download'),
    url('fileupload/bulk_upload', views.bulk_upload, name='bulk_upload'),
    url(r'^$', views.home, name='home'),
    url(r'^fileupload/', views.fileupload, name='fileupload'),
    path('delete_archive_files/<int:id>/<type>/', views.delete_archive_files, name='delete_archive_files'),
    path('dashboard/', views.dashboard_view, name='dashboard'),

    path('user_files/', views.user_files, name='user_files'),
    url(r'document_upload', views.document_upload, name='document_upload'),

    path('delete_files/<int:id>/<type>/', views.delete_files_files, name='delete_files_files'),
	
	#user files
    path('root_files/<int:pk>/<type>/<username>', views.root_files, name='root_files'),
    path('user_files/<int:id>/<type>', views.user_files, name='user_files'),
    path('user_files/favorite/<int:file_id>', views.is_favorite, name='is_favorite'),
    path('starred_documents', views.starred_docs, name='starred_documents'),
    path('download/requested_file/<int:id>', views.download_history, name='download_file_request'),
    url(r'downloaded_files', views.download_files, name='downloaded_files'),
    path('total-document', views.total_document, name='total_document'),
    url(r'^send_to_share', views.send_to_share, name='send_to_share'),
    path('approval_sent_for_share/<int:id>', views.send_to_share, name='share_document'),

    path('approval_for_sharing/<int:id>', views.for_approval, name='for_approval'),
    path('all_files_for_sharing/', views.files_for_approval, name='files_for_approval'),
    path('all_files_for_sharing/<int:id>', views.files_for_approval, name='files_for_approval'),
    path('shared_documents/', views.shared_document, name='shared_document'),
    path('all_shared_documents', views.shared_by_all, name='all_shared_document'),
    path('stop_sharing/<int:id>/', views.stop_sharing, name='stop_sharing'),

    path('searchresults/<int:pk>/', views.search_files, name='search_files'),
    path('meta_search/', views.meta_search, name='meta_search'),
    path('document_view/<int:file_id>', views.document_protection, name='protecting_doc'),
    path('archive_files/', views.archive_files, name='archive_files'),
    url(r'access_history_table', views.access_history_table, name='access_history_table'),

    path('share_document_to_user/<int:file_id>', views.share_document_to_user, name='share_document_to_user'),
    path('shared_by_other', views.shared_by_other, name='shared_by_other'),
    path('notifications', views.notification_of_files, name='notification_files'),

    path('reports', views.reports, name='reports'),
    path('reports/other_users_info', views.other_users_info, name='other_users_info'),
    path('reports/reports_of_user/<int:user_id>', views.reports_of_user, name='reports_of_user'),

    path('notifications/notification_request', views.share_notification_request, name='share_notification_request'),
    path('notification/mark_read/<int:id>', views.mark_read, name='mark_read'),

    #account
    path('approval_form_for_account_opening/<int:task_id>/', views.approval_form_for_account_opening,
         name='approval_form_for_account_opening'),

    #Notes
    path('notification/notes', views.notes, name='notes'),
    path('notification/notes/<note>', views.notes, name='notes'),
    path('discussions/', views.discussions, name='discussions'),
    path('scan_document/', views.scan_document, name='scan_document'),


    url('bulk_upload_for_files', views.bulk_upload_for_files, name='bulk_upload_for_files'),

    #Encryption
    path('encrypt_document/<int:file_id>', views.encrypt_document, name='encrypt_document'),
    path('documents/encryption', views.encryption, name='encryption'),

    #Share Externally
    path('share_document_to_user/externally/<int:file_id>', views.share_files_externally, name='share_files_externally'),
    url(r'^document_shared_externally/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.document_shared_externally, name='document_shared_externally'),
    path('download_externally/requested_file/<int:id>', views.download_externally, name='download_externally'),

        #Account open
    path('workflow_management/', views.workflow_management, name='workflow_management'),
    path('account_opening_approval', views.account_opening_approval, name='account_opening_approval'),
    url(r'account_open', views.account_open, name='account_open'),
    path('notification/mark_read_account/<int:id>', views.mark_read_account, name='mark_read_account'),
    url(r'workflow_management/approved_forms', views.approved_forms, name='approved_forms_for_AO'),
    url(r'workflow_management/rejected_forms', views.rejected_forms, name='rejected_forms_for_AO'),

    path('delete_notification_for_workflow/<int:notif_id>', views.delete_notification_for_workflow, name='delete_notification_for_workflow'),
    path('validate_filename/', views.validate_filename, name='validate_filename'),
    path('replace_file/', views.replace_file, name='replace_file'),
    path('restore_document/<int:file_id>', views.restore_document, name='restore_document'),
    path('check_valid_password/', views.check_valid_password, name='check_valid_password'),
    path('delete_sticky_notes/<int:note_id>', views.delete_sticky_notes, name='delete_sticky_notes'),
    path('edit_sticky_notes/<int:note_id>', views.edit_sticky_notes, name='edit_sticky_notes'),
    path('check_protection/<int:id>/<url_sub>/', views.check_protection, name='check_protection'),
    
    path('ask_replace_file_password/<int:file_id>/', views.ask_replace_file_password, name='ask_replace_file_password'),
    path('share_locked_file/<int:file_id>/', views.share_locked_file, name='share_locked_file'),
    
    path('table_request_form', views.table_request_form, name='table_request_form'),
    path('theme_management_selection', views.theme_management_selection, name='theme_management_selection'),
	
	#data to pdf
	path('data_to_excel', views.data_to_excel, name='data_to_excel'),
    path('data_to_pdf', views.data_to_pdf, name='data_to_pdf'),
    path('report_list', views.report_list, name='report_list'),

]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DMSproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from DMSapp import views as DMSapp_views
from DMSContact import views as DMSContact_views
from DMSpages import views as DMSpages_views
from DMSaccount import views as DMSaccount_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ajax_select import urls as ajax_select_urls

admin.site.site_header = "DMS Admin"
admin.site.site_title = "DMS Admin Portal"
admin.site.index_title = "Welcome to Document Management System!!"

urlpatterns = [
    # path('home/<DMS>', DMSapp_views.home, name='home'),
    url(r'^$', DMSapp_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('admin1', DMSaccount_views.admin, name='admin'),
    path('home/<DMS>', DMSapp_views.home, name='home'),
    path('home/', DMSapp_views.home, name='home'),
    url(r'^ajax_select/', include(ajax_select_urls)),
    path('signup/', DMSaccount_views.signup, name='signup'),
    path('login/', DMSaccount_views.login1, name='user_login'),
    path('password/', DMSaccount_views.change_password, name='change_password'),
    path('user_files/<int:id>/', DMSapp_views.user_files, name='user_files'),
    url(r'^', include(('DMSapp.urls', 'DMSapp'), namespace='DMS')),
    url(r'^', include(('DMSpages.urls', 'DMSpages'), namespace='DMSpages')),
    url(r'^', include(('DMSaccount.urls', 'DMSaccount'), namespace='DMSaccount')),
    url(r'^', include(('DMSloader.urls', 'DMSloader'), namespace='DMSloader')),
    url(r'^', include(('twofactor.urls', 'twofactor'), namespace='two_factor')),
    url(r'^', include(('WorkflowManagement.urls', 'WorkflowManagement'), namespace='WorkflowManagement')),

    path('root_files/<int:pk>/', DMSapp_views.root_files, name='root_files'),

    # for OTP
    path('sendOTP/<id>/', DMSaccount_views.send_otp, name='send_otp'),
    path('resendOTP/<id>/<mobile_no>/', DMSaccount_views.resend_otp, name='resendOTP'),
    path('enterOTP/<id>/<mobile_no>/', DMSaccount_views.enter_otp, name='enterOTP'),
    path('verifyOTP/<id>/<mobile_no>/', DMSaccount_views.verify_otp, name='verifyOTP'),
    # path('detectorAndTrainer/(?P<id>\d+)/',DMSaccount_views.detectorAndTrainer, name='detectorAndTrainer'),
    path('contact/', DMSContact_views.contact, name='contact'),
    path('load_pages/', DMSpages_views.home, name='load_pages'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += [url(r'^captcha/', include('captcha.urls')), ]


urlpatterns += [url(r'^ckeditor/', include('ckeditor_uploader.urls')), ]

WorkflowManagement/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [

    path('workflow_form_selection', views.workflow_form_selection, name='workflow_form_selection'),
    path('workflow_management_selection/<int:queryset_id>', views.workflow_management_selection, name='workflow_management_selection'),
    path('workflow_management_form_view/<int:queryset_id>', views.workflow_form_view, name='workflow_form_view'),
    path('removeField/<int:queryset_id>/<label>', views.remove_field, name='removeField'),
    path('validate_label_name_workflow/<int:queryset_id>', views.validate_label, name='validate_label'),
    path('validate_mobile_number_workflow/', views.checkmobile, name='validate_mobile_number_workflow'),
    path('validate_pan_number_workflow/', views.validate_pan_number, name='validate_pan_number'),
    path('validate_aadhar_number/', views.validate_aadhar_number, name='validate_aadhar_number'),
    path('validateEmail/', views.validateEmail, name='validateEmail'),
    path('confirm_workflow/<int:queryset_id>', views.confirm_workflow, name='confirm_workflow'),
    path('toggle_button/<int:wf_id>', views.toggle_button, name='toggle_button'),
    path('validateOnlyAlphabets/', views.validateOnlyAlphabets, name='validateOnlyAlphabets'),
    path('workflow_management', views.workflow_management, name='workflow_management'),
    path('delete_workflow/<int:id>', views.delete_workflow, name='delete_workflow'),
    path('validateAlphaNumeric/', views.validateAlphaNumeric, name='validateAlphaNumeric'),
    path('workflow_selection_for_department', views.workflow_selection_for_department, name='workflow_selection_for_department'),
    path('fill_workflow_form/<int:queryset_id>', views.fill_workflow_form, name='fill_workflow_form'),
    path('all_wf_forms/<int:queryset_id>/<status>', views.all_wf_forms, name='all_wf_forms'),
    path('all_wf_forms/<int:queryset_id>/<status>/<int:read>', views.all_wf_forms, name='all_wf_forms'),
    path('all_workflow_for_maker', views.all_workflow_for_maker, name='all_workflow_for_maker'),
    path('all_user_forms_workflow/<int:forms_pk>', views.all_user_forms_workflow, name='all_user_forms_workflow'),
    path('all_user_forms_workflow/<int:forms_pk>/<int:read>', views.all_user_forms_workflow, name='all_user_forms_workflow'),
    path('edit_workflow_maker/<int:user_data_pk>', views.edit_workflow_maker, name='edit_workflow_maker'),
    path('submit_to_checker/<int:user_data_pk>', views.submit_to_checker, name='submit_to_checker'),
    path('all_workflow_for_checker', views.all_workflow_for_checker, name='all_workflow_for_checker'),
    path('all_wf_for_approval/<int:wf_id>', views.all_wf_for_approval, name='all_wf_for_approval'),
    path('customer_data_for_approval/<int:data_id>', views.customer_data_for_approval, name='customer_data_for_approval'),
    path('customer_data_for_approval/<int:data_id>/<int:read>', views.customer_data_for_approval, name='customer_data_for_approval'),
    path('checker_for_approval/<int:data_id>', views.checker_for_approval, name='checker_for_approval'),

    path('all_rejected_forms/<int:form_id>', views.all_rejected_forms, name='all_rejected_forms'),
    path('all_rejected_forms/<int:form_id>/<int:read>', views.all_rejected_forms, name='all_rejected_forms'),
    path('delete_form/<int:form_id>', views.delete_form, name='delete_form'),

    url('image_ocr', views.image_ocr ,name='image_ocr'),

    path('scan_documents', views.scan_documents_sanelib, name='scan_documents_sanelib'),
    path('document_scan_parameter', views.document_scan_parameter, name='document_scan_parameter'),

    path('scanned_images', views.scanned_images, name='scanned_images'),
    path('scanned_user_data', views.scanned_user_data, name='scanned_user_data'),
    path('submit_tag_option', views.submit_tag_option, name='submit_tag_option'),
    path('crop_popup/', views.crop_popup, name='crop_popup'),
    path('submit_cropped_image', views.submit_cropped_image, name='submit_cropped_image'),
    path('save_rotated_image', views.save_rotated_image, name='save_rotated_image'),

    path('ajax_scanned_document', views.ajax_scanned_document, name='ajax_scanned_document'),
    path('ajax_login_call', views.ajax_login_call, name='ajax_login_call'),

    # New Changes in Workflow

    #path('workflowProcess', views.workflowProcess, name='workflowProcess'),

    path('workflow_process/<int:id>',views.workflow_process,name='workflow_process'),
    path('workflow_process/workflowLogin', views.workflowLogin, name='workflowLogin'),
    path("workflowDocsLogin", views.workflowDocsLogin, name='workflowDocsLogin'),
    path('fetch_data_from_finacle', views.fetch_data_from_finacle, name='fetch_data_from_finacle'),
    path('confirm_finacle_entry/<int:user_data_pk>', views.confirm_finacle_entry, name='confirm_finacle_entry'),

    path('workflow_docs', views.workflow_docs, name='workflow_docs'),
    path('workflow_docs_search', views.workflow_docs_search, name='workflow_docs_search'),

    path('download_workflow_docs/<int:value>/<str_value>', views.download_workflow_docs, name="download_workflow_docs"),
    path('download_workflow_docs/<int:value>', views.download_workflow_docs, name="download_workflow_docs"),
    path('confirm_workflow_docs', views.confirm_workflow_docs, name="confirm_workflow_docs"),

    path('del_workflow_docs/<int:value>/<str_value>', views.del_workflow_docs, name="del_workflow_docs"),
    path('del_workflow_docs/<int:value>', views.del_workflow_docs, name="del_workflow_docs"),

    path('view_mis_report', views.view_mis_report, name='view_mis_report'),
    path('save_image_workflow_process', views.save_image_workflow_process, name="save_image_workflow_process"),
    path('workflow_docs_for_version', views.workflow_docs_for_version, name='workflow_docs_for_version'),
    url(r'^download_version_file/(?P<path>.*)$', views.download_version_file, name='download_version_file'),


    path('ajax_call_for_files', views.ajax_call_for_files, name='ajax_call_for_files'),
    path('workflow_docs_list', views.workflow_docs_list, name="workflow_docs_list"),
    path('view_approved_document/<doc>/<doc_id>', views.view_approved_document, name="view_approved_document"),
    
    path('extract_account_numner_nodata/<value>', views.extract_account_numner_nodata, name='extract_account_numner_nodata'),
    path('delete_workflow_scanned_data/<int:value>', views.delete_workflow_scanned_data, name='delete_workflow_scanned_data'),

    path('download_workflow_document_for_ckyc/', views.download_workflow_document_for_ckyc, name='download_workflow_document_for_ckyc'),
    path('workflow_reports', views.workflow_reports, name='workflow_reports'),
]


urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DMSapp/templates/other_files/account_opening_files.html
{% extends 'header.html' %}
{% block body_block %}
{% load i18n %}
{% load staticfiles %}
{% if user.is_authenticated %}

<p class="breadcrumb breadcrumb_lbl"><a href="{%url 'home'%}">Home</a> / <a href="{%url 'DMS:notification_files' %}">Notifications</a></p>
<br>
<p class="breadcrumb  accord"><strong> All Accounts </strong></p>
<br>
    <table id="notification_list" class = 'table'>
            <thead >
                <tr>
                    <th> {% trans 'Sr. No.' %} </th>
                    <th> {% trans 'Customer Name' %} </th>
                    <th> {% trans 'Identity' %}</th>
                    <th> {% trans 'Identity Proof' %} </th>
                    <th> {% trans 'Pan Card' %} </th>
                    <th> {% trans 'Photo' %} </th>
                    <th> {% trans 'Signature' %} </th>
                    <th> {% trans 'Status' %} </th>
                    <th> {% trans 'Change' %} </th>
                </tr>
            </thead>
            <tbody>
                    {% for task in all_accounts %}
                        <tr>
                            <td> {{ forloop.counter }} </td>
                            <td> {{ task.customer_name }} </td>
                            <td> {{ task.identity }} </td>
                            <td> <a href="{{ task.identity_proof.url}}" class="btn btn-primary">Identity proof
                                 </a>
                            </td>
                            <td>
                                <a href="{{ task.Pan_Card.url }}" class="btn btn-primary">Pan Card
                                </a>
                            </td>

                            <td>
                                <a href="{{ task.Photo.url }}" class="btn btn-primary">Photo
                                </a>
                            </td>
                            <td><a href="{{ task.Signature.url }}" class="btn btn-primary">Signature
                                </a>
                                 </td>
                             <td> {{ task.status }} </td>
                            <td>
                                <button type="button" class="btn btn-info modal_type" data-url="{% url 'DMS:approval_form_for_account_opening' task.id %}">Edit
                                  </button>
                            </td>
                        </tr>
                    {% endfor %}
            </tbody>
    </table>


    <div class="modal fade" id="modal_id">
      <div class="modal-dialog">
        <div class="modal-content"></div>
      </div>
    </div>

   {% else %}
    You are not Logged In. Please login
   {% endif %}

<script>
      $('.modal_type').on("click",function (){
         $.ajax({
           url: $(this).attr("data-url"),
           dataType: 'json',
           beforeSend: function () {
             $("#modal_id").modal("show");
           },
           success: function (data) {
             $("#modal_id .modal-content").html(data.html_form);
           }
         });

      });
</script>

{% endblock %}

DMSapp/templates/other_files/account_opening_form.html
{% extends 'header.html' %}
{% block body_block %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}

<form action="#" method="post" enctype="multipart/form-data" autocomplete="off">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Submit">
</form>

{% endif %}
{% endblock %}

DMSapp/templates/other_files/all_files_for_encryption.html
{% extends 'header.html' %}
{% load static %}
{% load i18n %}
{% block body_block %}
{% if user.is_authenticated %}
<style>
    td,th
    {
        text-align:center;
    }
    #no{
      color:gray;
    }
</style>


<div class="breadcrumb_dms">
        <nav>
            <ol class="breadcrumb breadcrumb_lbl">
                <li class="breadcrumb-item"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a></li>
				 <li class="breadcrumb-item active"><a href="{% url 'DMS:dashboard' %}">{% trans 'Document Management' %}</a></li>
				 <li class="breadcrumb-item active">{% trans 'Encrypt Document' %} </li>
            </ol>
        </nav>
    </div>

<div style="float:left;">
  <form class="form-inline" autocomplete="off">
    <input class="form-control mr-sm-2" type="text" style="width:300px;" placeholder="{% trans 'Search By File Name or User Name' %}" aria-label="Search" name="searchMe" id="more_search" data-url="{% url 'DMS:encryption' %}">

  </form>
</div><br><br>


<div class="table-responsive">
 <table class = 'table table-bordered table-hover table-sm table-striped access_history_table' id="book-table" style="white-space:nowrap">
      <thead class='table-info'>
      <tr>
        <th>{% trans 'Sr. No.' %}</th>
        <th>{% trans 'Uploader' %}</th>
        <th>{% trans 'Filename' %}</th>
        <th>{% trans 'File Type' %} </th>
        <th>{% trans 'Download' %} </th>
        <th>{% trans 'Encrypt' %} </th>



      </tr>
      </thead>
      <tbody>
        {% include 'files/encrypt_files.html' %}

      </tbody>
    </table>

    <div class="mypage">
           {% include 'files/pagination.html' %}
         </div>
       <div class="modal fade" id="modal-book">
         <div class="modal-dialog">
           <div class="modal-content"></div>
         </div>
       </div>
     </div>

</div>
{% else %}
  You are not logged in.
{% endif %}
<script type="text/javascript">


  $('#more_search').on('keyup', function() {
    if ($(this).val()){

      var val = this.value;
      console.log(val);
    }else{

      var val='0'
    }

    var url = $(this).attr("data-url");

    $.ajax({
            url: url,
            data:{
              'searchVal' : val
            },

            success: function (data) {
              if (data.form_is_valid) {

                $("#book-table tbody").html(data.html_book_list);
                $(".mypage").html(data.page_div);
              }
              else {

                $("#modal-book .modal-content").html(data.html_form);
              }
            }
          });
          return false;
  });

</script>




{% endblock %}

DMSapp/templates/other_files/delete_notification.html
{%load static%}
{% load i18n %}
{% if files %}
{% for notif in files %}
        <tr class="{% if notif.fields.unread %} a1 {% endif %}" id="myclass_{{notif.pk}}">
            {% if notif.fields.receiver == request.user.id %}
            <td> {{ notif.fields.srNo }} </td>
            <td style="text-align:left"> {{notif.fields.sender}} has changed the status of Application Form  <i><u>{{ notif.fields.customer_id }}</u></i>  to {{notif.fields.type}} for {{ notif.fields.wf_name }}</td>
            <td>
                <a class="btn btn-info btn-sm btn-notification" title="Change Record" data-cities-url="{% url 'DMS:mark_read_account' notif.pk %}">
                     <i class="fa fa-envelope {% if not notif.fields.unread %} fa-envelope-open {% endif %}">
                     </i>
                 </a>
            </td>
            <td>
                <button type="button" data-cities-url="{% url 'DMS:delete_notification_for_workflow' notif.pk %}" title="Delete Notification" class="btn btn-sm btn-danger deletebtn"><i class="fa fa-trash"></i></button>
            </td>
	    <td>
                {% if notif.fields.type == 'Rejected' %}
                <a  href="{% url 'WorkflowManagement:all_rejected_forms' notif.fields.status notif.pk %}" title="Check Record" class="btn btn-sm btn-info"><i class="fa fa-link"></i></a>
                {% elif notif.fields.type == 'Drafted' %}
                <a href="{% url 'WorkflowManagement:customer_data_for_approval' notif.fields.status notif.pk %}" title="Check Record" class="btn btn-sm btn-info"><i class="fa fa-link"></i></a>
                {% elif notif.fields.type == 'Approved' %}
                <a href="{% url 'WorkflowManagement:all_wf_forms' notif.fields.wf_id 'Approved' notif.pk %}" title="Check Record" class="btn btn-sm btn-info"><i class="fa fa-link"></i></a>
                {% elif notif.fields.type == 'Pending' %}
                <a href="{% url 'WorkflowManagement:all_user_forms_workflow' notif.fields.status notif.pk %}" title="Check Record" class="btn btn-sm btn-info"><i class="fa fa-link"></i></a>
                {% endif %}
            </td>
            {%endif%}

        </tr>
    {% endfor %}
{% else %}
<tr>
    <td colspan="5"><h1 id="no">{% trans 'No Records Found' %}</h1></td>
  </tr>
{% endif %}

<script src="{% static 'javascript/notification.js' %}"></script>

DMSapp/templates/other_files/document_shared_externally.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        {% if file.is_protected %} File is protected with a password. To view or download the same,
                Please enter the password..!! {% endif %} <br>

        <strong>File Name:</strong> {{ file.Filename }}<br>
        <strong>Download File:</strong> <a data-cities-url="{% url 'DMS:download' file.id 'user_files' %}" class = "btn btn-primary btn-sm btn_download_externally" name="{{file.id}}">Download File
            <span class="fa {% if file.is_protected %} fa-lock {% endif %}"></span>
        </a>

<script src="{% static 'javascript/externally_shared_doc.js' %}"></script>
{% endblock %}

DMSapp/templates/other_files/forms.html
{% extends 'header.html' %}
{% if user.is_authenticated %}
{% block body_block %}

<div>
<a href="{% url 'home' %}">Home</a> / <a href="{%url 'DMS:workflow_management'%}">Workflow Management</a>
</div>

<h1 class="page-header">
    <small> {% block title %}{% endblock %}</small>
  </h1>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"></h3>
        </div>
        <div class="list-group">
          <a href="{% url 'DMS:approved_forms_for_AO' %}" class="list-group-item">
            Approved Forms
          </a>
          <a href="{% url 'DMS:rejected_forms_for_AO' %}" class="list-group-item">
            Rejected Forms
          </a>
        </div>
      </div>
    </div>

<div class="col-md-9">
  {% block form_content %}
  {% endblock %}
</div>
  </div>
{% endblock %}
{% endif %}

DMSapp/templates/other_files/theme_management.html
{% extends 'header.html' %}
{% load i18n %}
{% block body_block %}
<title> {% block title %} Themes Management {% endblock %} </title>
<br/>
<div class="breadcrumb_dms">
        <nav>
            <ol class="breadcrumb breadcrumb_lbl">
                <li class="breadcrumb-item"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a></li>
				 <li class="breadcrumb-item active"><a href="{% url 'DMSaccount:dms_settings' %}">{% trans 'Settings'%}</a></li>
				 <li class="breadcrumb-item active">{% trans 'Theme Management' %}</li>
            </ol>
        </nav>
    </div>    


      <form action="{% url 'DMS:theme_management_selection' %}" method="post">
          {% csrf_token %}
            {{ form.as_p }}

          <button type="submit" value="Submit">Button</button>

        </form>


{% endblock %}

DMSapp/templates/other_files/workflow_management.html
{% extends 'header.html' %}
{% load staticfiles %}
{% block body_block %}
<style>
  div.absolute {
  position: absolute;
  top: 300px;
  right: 100px;
  width: 400px;
  height: 200px;
  border: 2px solid ;
}
</style>

<div>
<a href="{% url 'DMS:home' %}">Home</a>
</div>
<br/>

<p><a href="{% url 'DMS:account_open' %}">Fill Form</a></p>
<p><a href="#">Scan Document</a></p>

<div class="absolute">
    <h3>Processed forms.</h3>
    <p><a href="{% url 'DMS:approved_forms_for_AO' %}">Approved Forms</a></p>

</div>

{% endblock %}