DMSaccount/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import path

from . import views

urlpatterns = [
    
    path('toggle_security/<int:id>', views.toggle_security, name='toggle_security'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^profile/$', views.user_profile, name='user_profile'),
    path('profile/<username>/', views.user_profile, name='user_profile'),
    path('profile/edit/<int:pk>', views.edit_profile, name='edit_profile'),

    path('all_users', views.all_users, name='all_users'),
    path('all_users/<username>/', views.delete_users, name='delete_users'),
    path('userprofile_del/<int:pk>', views.delete_users, name='deactivate_user_view'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
        name='activate'),

    path('security/<int:id>/', views.select_security, name='select_security'),
    url(r'security/', views.security, name='select_security'),
    #path('toggle_security/<int:id>', views.toggle_security, name='toggle_security'),
    path('signup_complete', views.signup_complete, name='signup_complete'),
    path('signup_completed', views.signup_completed, name='signup_completed'),

    url(r'^reset_password/', views.reset_password, name='reset'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.reset_token,
        name='reset_token'),
    url(r'password_reset_complete', views.password_reset_complete, name='password_reset_complete'),


    path('administration', views.administration, name='administration'),
    path('administration/user_roles', views.user_roles, name='user_roles'),
    path('settings', views.dms_settings, name='dms_settings'),

    #validations
    url(r'^validate_username/$', views.validate_username, name='validate_username'),
    url(r'^validate_email/$', views.validate_email, name='validate_email'),
    url(r'^validate_pass/$', views.validate_pass, name='validate_pass'),
    path('snataken/', views.snataken, name='snataken'),
    path('snatakenforlogin/', views.snatakenforlogin, name='snatakenforlogin'),
    path('camera/<user>/<forType>/', views.camera, name='camera'),
    path('camera2/<user>/', views.camera2, name='camera2'),
    path('page_records_setting', views.page_records_setting, name='page_records_setting'),


    path('administration/user_roles/change_role_for_user/<int:user_id>', views.change_role_for_user, name='change_role_for_user'),
    path('change_password',views.change_password,name='change_password'),
    path('check_user_password/',views.check_user_password,name='check_user_password'),

    path('confirm_login_if_stored_session/<session>', views.check_stored_session, name='check_stored_session'),
    path('user_logout_on_confirm', views.user_logout_on_confirm, name='user_logout_on_confirm'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [url(r'^captcha/', include('captcha.urls')), ]

DMSapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [

	path('show_delete_popup/<int:file_id>/', views.show_delete_popup, name='show_delete_popup'),
    path('download/file/<int:id>/<type>/', views.download_protection, name='download'),
    url('fileupload/bulk_upload', views.bulk_upload, name='bulk_upload'),
    url(r'^$', views.home, name='home'),
    url(r'^fileupload/', views.fileupload, name='fileupload'),
    path('delete_archive_files/<int:id>/<type>/', views.delete_archive_files, name='delete_archive_files'),
    path('dashboard/', views.dashboard_view, name='dashboard'),

    path('user_files/', views.user_files, name='user_files'),
    url(r'document_upload', views.document_upload, name='document_upload'),

    path('delete_files/<int:id>/<type>/', views.delete_files_files, name='delete_files_files'),
	
	#user files
    path('root_files/<int:pk>/<type>/<username>', views.root_files, name='root_files'),
    path('user_files/<int:id>/<type>', views.user_files, name='user_files'),
    path('user_files/favorite/<int:file_id>', views.is_favorite, name='is_favorite'),
    path('starred_documents', views.starred_docs, name='starred_documents'),
    path('download/requested_file/<int:id>', views.download_history, name='download_file_request'),
    url(r'downloaded_files', views.download_files, name='downloaded_files'),
    path('total-document', views.total_document, name='total_document'),
    url(r'^send_to_share', views.send_to_share, name='send_to_share'),
    path('approval_sent_for_share/<int:id>', views.send_to_share, name='share_document'),

    path('approval_for_sharing/<int:id>', views.for_approval, name='for_approval'),
    path('all_files_for_sharing/', views.files_for_approval, name='files_for_approval'),
    path('all_files_for_sharing/<int:id>', views.files_for_approval, name='files_for_approval'),
    path('shared_documents/', views.shared_document, name='shared_document'),
    path('all_shared_documents', views.shared_by_all, name='all_shared_document'),
    path('stop_sharing/<int:id>/', views.stop_sharing, name='stop_sharing'),

    path('searchresults/<int:pk>/', views.search_files, name='search_files'),
    path('meta_search/', views.meta_search, name='meta_search'),
    path('document_view/<int:file_id>', views.document_protection, name='protecting_doc'),
    path('archive_files/', views.archive_files, name='archive_files'),
    url(r'access_history_table', views.access_history_table, name='access_history_table'),

    path('share_document_to_user/<int:file_id>', views.share_document_to_user, name='share_document_to_user'),
    path('shared_by_other', views.shared_by_other, name='shared_by_other'),
    path('notifications', views.notification_of_files, name='notification_files'),

    path('reports', views.reports, name='reports'),
    path('reports/other_users_info', views.other_users_info, name='other_users_info'),
    path('reports/reports_of_user/<int:user_id>', views.reports_of_user, name='reports_of_user'),

    path('notifications/notification_request', views.share_notification_request, name='share_notification_request'),
    path('notification/mark_read/<int:id>', views.mark_read, name='mark_read'),

    #account
    path('approval_form_for_account_opening/<int:task_id>/', views.approval_form_for_account_opening,
         name='approval_form_for_account_opening'),

    #Notes
    path('notification/notes', views.notes, name='notes'),
    path('notification/notes/<note>', views.notes, name='notes'),
    path('discussions/', views.discussions, name='discussions'),
    path('scan_document/', views.scan_document, name='scan_document'),


    url('bulk_upload_for_files', views.bulk_upload_for_files, name='bulk_upload_for_files'),

    #Encryption
    path('encrypt_document/<int:file_id>', views.encrypt_document, name='encrypt_document'),
    path('documents/encryption', views.encryption, name='encryption'),

    #Share Externally
    path('share_document_to_user/externally/<int:file_id>', views.share_files_externally, name='share_files_externally'),
    url(r'^document_shared_externally/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.document_shared_externally, name='document_shared_externally'),
    path('download_externally/requested_file/<int:id>', views.download_externally, name='download_externally'),

        #Account open
    path('workflow_management/', views.workflow_management, name='workflow_management'),
    path('account_opening_approval', views.account_opening_approval, name='account_opening_approval'),
    url(r'account_open', views.account_open, name='account_open'),
    path('notification/mark_read_account/<int:id>', views.mark_read_account, name='mark_read_account'),
    url(r'workflow_management/approved_forms', views.approved_forms, name='approved_forms_for_AO'),
    url(r'workflow_management/rejected_forms', views.rejected_forms, name='rejected_forms_for_AO'),

    path('delete_notification_for_workflow/<int:notif_id>', views.delete_notification_for_workflow, name='delete_notification_for_workflow'),
    path('validate_filename/', views.validate_filename, name='validate_filename'),
    path('replace_file/', views.replace_file, name='replace_file'),
    path('restore_document/<int:file_id>', views.restore_document, name='restore_document'),
    path('check_valid_password/', views.check_valid_password, name='check_valid_password'),
    path('delete_sticky_notes/<int:note_id>', views.delete_sticky_notes, name='delete_sticky_notes'),
    path('edit_sticky_notes/<int:note_id>', views.edit_sticky_notes, name='edit_sticky_notes'),
    path('check_protection/<int:id>/<url_sub>/', views.check_protection, name='check_protection'),
    
    path('ask_replace_file_password/<int:file_id>/', views.ask_replace_file_password, name='ask_replace_file_password'),
    path('share_locked_file/<int:file_id>/', views.share_locked_file, name='share_locked_file'),
    
    path('table_request_form', views.table_request_form, name='table_request_form'),
    path('theme_management_selection', views.theme_management_selection, name='theme_management_selection'),
	
	#data to pdf
	path('data_to_excel', views.data_to_excel, name='data_to_excel'),
    path('data_to_pdf', views.data_to_pdf, name='data_to_pdf'),
    path('report_list', views.report_list, name='report_list'),

]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DMSproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from DMSapp import views as DMSapp_views
from DMSContact import views as DMSContact_views
from DMSpages import views as DMSpages_views
from DMSaccount import views as DMSaccount_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ajax_select import urls as ajax_select_urls

admin.site.site_header = "DMS Admin"
admin.site.site_title = "DMS Admin Portal"
admin.site.index_title = "Welcome to Document Management System!!"

urlpatterns = [
    # path('home/<DMS>', DMSapp_views.home, name='home'),
    url(r'^$', DMSapp_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('admin1', DMSaccount_views.admin, name='admin'),
    path('home/<DMS>', DMSapp_views.home, name='home'),
    path('home/', DMSapp_views.home, name='home'),
    url(r'^ajax_select/', include(ajax_select_urls)),
    path('signup/', DMSaccount_views.signup, name='signup'),
    path('login/', DMSaccount_views.login1, name='user_login'),
    path('password/', DMSaccount_views.change_password, name='change_password'),
    path('user_files/<int:id>/', DMSapp_views.user_files, name='user_files'),
    url(r'^', include(('DMSapp.urls', 'DMSapp'), namespace='DMS')),
    url(r'^', include(('DMSpages.urls', 'DMSpages'), namespace='DMSpages')),
    url(r'^', include(('DMSaccount.urls', 'DMSaccount'), namespace='DMSaccount')),
    url(r'^', include(('DMSloader.urls', 'DMSloader'), namespace='DMSloader')),
    url(r'^', include(('twofactor.urls', 'twofactor'), namespace='two_factor')),
    url(r'^', include(('WorkflowManagement.urls', 'WorkflowManagement'), namespace='WorkflowManagement')),

    path('root_files/<int:pk>/', DMSapp_views.root_files, name='root_files'),

    # for OTP
    path('sendOTP/<id>/', DMSaccount_views.send_otp, name='send_otp'),
    path('resendOTP/<id>/<mobile_no>/', DMSaccount_views.resend_otp, name='resendOTP'),
    path('enterOTP/<id>/<mobile_no>/', DMSaccount_views.enter_otp, name='enterOTP'),
    path('verifyOTP/<id>/<mobile_no>/', DMSaccount_views.verify_otp, name='verifyOTP'),
    # path('detectorAndTrainer/(?P<id>\d+)/',DMSaccount_views.detectorAndTrainer, name='detectorAndTrainer'),
    path('contact/', DMSContact_views.contact, name='contact'),
    path('load_pages/', DMSpages_views.home, name='load_pages'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += [url(r'^captcha/', include('captcha.urls')), ]


urlpatterns += [url(r'^ckeditor/', include('ckeditor_uploader.urls')), ]

DMSapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core import validators
from django.core.validators import FileExtensionValidator
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from .validators import validate_file_extension, pdf_file_validation
from .models import FileUpload, Project, SharedDocument, Notes
from .choices import THEME_CHOICES

User = get_user_model()

alphanumeric = validators.RegexValidator(r'^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')


class FileUploadForm(forms.ModelForm):
	CHOICES = (
                ('', _('--Select--')), 
		('Documents', _('Documents')),
		('Invoice', _('Invoice')),
		('HR Documents', _('HR Documents'))
	)

	Uploader = forms.CharField(label=_('Uploaded By'),required=True, validators=[alphanumeric], widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':_('Uploaded By')}))
	File1 = forms.FileField(label=_('File'),widget=forms.FileInput(attrs={'id': 'yz',  'class': 'for_word'}))
	category = forms.ChoiceField(label=_('Category'), choices=CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

	class Meta:
		model = FileUpload
		fields = ['Uploader', 'category', 'File1']


class Dashboard(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', )


class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['name']


class FavoriteForm(forms.ModelForm):
	class Meta:
		model = FileUpload
		fields = ['is_favorite']


class SharedDocumentForm(forms.ModelForm):
	class Meta:
		model = SharedDocument
		fields = ('status', 'Comment')
		widgets = {
			'Comment': forms.Textarea(attrs={'class':'form-control','rows': 4, 'cols': 20}),
			'status' : forms.Select(attrs={'class':'form-group'}),
		}


class SharedDocumentRequestForm(forms.ModelForm):

	requested_user = forms.ModelChoiceField(queryset=User.objects.all(), empty_label="--Select--")

	class Meta:
		model = SharedDocument
		fields = ('requested_user', )


class ChoiceForm(forms.Form):
	CHOICES= (
		('0', _('All')),
		('1', _('Date')),
		('2', _('File Type'))

		)
	Sort_by = forms.ChoiceField(label=_('Sort By'),choices=CHOICES, widget=forms.Select(attrs={
			'class': 'choicy',
			'id':'changeId',
		})
		)


class NewChoiceForm(forms.Form):
	CHOICES= (
		('0', _('All')),
		('1', _('Date'))

		)
	Sort_by = forms.ChoiceField(label=_('Sort By'),choices=CHOICES, widget=forms.Select(attrs={
			'class': 'choicy',
			'id':'changeId',
		})
		)


class NoteForm(forms.ModelForm):
	title = forms.CharField(label=_('Title'), max_length=20, validators=[alphanumeric], widget=forms.TextInput(attrs={'class': 'col-xs-4  col-form-label'}))
	note = forms.CharField(label=_('Note') , max_length=150, widget=forms.TextInput(attrs={'class': 'col-xs-4  col-form-label'}))

	class Meta:
		model = Notes
		fields = ('title', 'note', )


class BulkFileUploadForm(forms.ModelForm):
	File1 = forms.FileField(widget=forms.FileInput(attrs={'id': 'yz'}))

	class Meta:
		model = FileUpload
		fields = ['File1']


class SharedDocumentExternally(forms.Form):
	name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name', 'autocomplete':'off'}))
	# text = forms.TextInput(attrs={'rows': 4, 'cols': 20})
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email', 'autocomplete':'off'}))


class MisQueryForm(forms.Form):
	table_request = (
		('', '--Select--'),
		('User', 'User Data'),
		('FileUpload', 'Uploaded Documents'),
		('Workflow_Management', 'Workflow Management'),
	)
	query = forms.CharField(label=_('Query'), widget=forms.Textarea(attrs={'rows': 8, 'cols': 50}))


class ThemeManagementForm(forms.Form):
	theme = forms.ChoiceField(choices=THEME_CHOICES, label=_('Theme'), widget=forms.Select(), required=False)

DMSapp/templates/confirm_delete.html
{% extends 'header.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<form method="post" autocomplete="off">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

DMSapp/templates/data_to_pdf_template.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h2>Sales Funnel Report - National</h2>
     {{ national_pivot_table }}
</body>
</html>

DMSapp/templates/discussions.html
{% extends 'header.html' %}
{% load staticfiles %}
{% block body_block %}
{% if user.is_authenticated %}
<style>
  img {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
</style>
<br/>
<p class="breadcrumb breadcrumb_lbl"><a href="{% url 'DMS:home' %}">Home&nbsp;</a> / Discussions</p>
<div class="container-flex">
<img src="{% static 'images/coming-soon.jpg' %}" class="rounded mx-auto d-block img-fluid" alt="Coming Soon">
</div>
<br/><br/>
{% else %}

Please login!

{% endif %}

{% endblock %}

DMSapp/templates/document_upload.html
{% extends 'header.html' %}
{% load staticfiles %}
{% load i18n %}

{% block body_block %}
<br/>

<div class="breadcrumb_dms">
        <nav>
            <ol class="breadcrumb breadcrumb_lbl">
                <li class="breadcrumb-item"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item active">{% trans 'Document Upload' %}</li>
            </ol>
        </nav>
    </div>
<br>
<p class="breadcrumb  accord"><a href="{% url 'DMS:fileupload' %}" class="kClass">{% trans 'Document Upload' %}</a> </p>



<script>
  $('.kClass').on('click',function(){
    localStorage.clear();

  })
</script>
{% endblock %}

DMSapp/templates/history_table.html
{% extends 'header.html' %}
{% load staticfiles %}
{% load i18n %}
{% block body_block %}
<title> {% block title %} Access History {% endblock %} </title>
{% if user.is_authenticated %}
<style>
    td,th
    {
    text-align:center;
    }
    #no{
        color:gray;
        }

</style>
<br/>

<div class="breadcrumb_dms">
        <nav>
            <ol class="breadcrumb breadcrumb_lbl">
                <li class="breadcrumb-item"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item active">{% trans 'Access History' %}</li>
            </ol>
        </nav>
    </div>

<p class="breadcrumb  accord">{% trans 'Access History' %}</p>
<div style="float:left;">
  <form class="form-inline" autocomplete="off">
    <input class="form-control mr-sm-2" type="text" style="width:300px;" placeholder="{% trans 'Search By File Name or User Name' %}" aria-label="Search" name="searchMe" id="more_search" data-url="{% url 'DMS:access_history_table' %}">

  </form>
</div>
<div align="right">
<i class="fa fa-file-excel-o fa-2x" data-toggle="tooltip" title="Download Report in Excel" 
		 data-cities-url="{% url 'DMS:data_to_excel' %}" data-placement="bottom" style="color:green" id="btnExportToExcel" aria-hidden="true"></i>
<i class="fa fa-file-pdf-o fa-2x" data-toggle="tooltip" title="Download Report in PDF" 
		data-cities-url="{% url 'DMS:data_to_pdf' %}" data-placement="bottom" style="color:red" id="btnExportToPdf" aria-hidden="true"></i>
</div>
<div class="table-responsive">
        <table id="book-table" class = 'table table-bordered table-hover table-striped access_history_table' style="white-space:nowrap">
            <thead class='table-info'>
                <tr>

                    <th>{% trans 'Sr. No.' %}</th>
                    <th>{% trans 'User ID' %} </th>
                    <th>{% trans 'User Name' %} </th>
                    <th>{% trans 'File Name' %} </th>
                    <th>{% trans 'File Type' %}</th>
                    <th>{% trans 'Action Date' %} </th>
                    <th>{% trans 'Action' %} </th>
                </tr>
            </thead>
            {% if files %}
            <tbody>
                {% include 'files/history_list.html' %}
            </tbody>
            {% else %}
             <tr>
                <td colspan="7"><h1 id="no">No Records Found</h1></td>
              </tr>
            {% endif %}
        </table>
        {% if files %}
        <div class="mypage">
          {% include 'files/pagination.html' %}
        </div>
        {% endif %}
</div>
{% else %}
  You are not logged in.
{% endif %}
<script type="text/javascript">


  $('#more_search').on('keyup', function() {
    if ($(this).val()){

      var val = this.value;
      console.log(val);
    }else{

      var val='0'
    }

    var url = $(this).attr("data-url");

    $.ajax({
            url: url,
            data:{
              'searchVal' : val
            },

            success: function (data) {
              if (data.form_is_valid) {

                $("#book-table tbody").html(data.html_book_list);
                $(".mypage").html(data.page_div);
              }
              else {

                $("#modal-book .modal-content").html(data.html_form);
              }
            }
          });
          return false;
  });

</script>

<script src="{% static 'javascript/access_history_scripts.js' %}"></script>
{% endblock %}

DMSapp/templates/home_bkp.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<style>
.image {
  opacity: 1;
  width: 18%;
  height: auto;
  transition: .5s ease;
  backface-visibility: hidden;
}

.image:hover  {
  opacity: 0.3;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}
</style>
    <h1>Welcome to the DMS !</h1>
    {% if user.is_superuser %}
        <h2>Hello {{ user.username }}</h2>

        <div align="right">
            <form class="form-inline my-2 my-lg-0" action="{% url 'DMS:search_files' user.pk %}" autocomplete="off">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="searchMe">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

        <div class="topnav">
            <p> <a href='#'> Dashboard </a> </p>
            <p> <a href="{%url 'DMS:dashboard'%}" > Document Management </a></p>
            <p> <a href="{% url 'DMSaccount:user_profile'%} "> My Account </a> </p>
            <p><a href="{% url 'DMSaccount:all_users'%}">User Management</a></p>
            <p> <a href="{% url 'DMSaccount:select_security' %}"> Setting </a></p>
        </div>

             <div align="left">
                 {% include 'partial_user_info/partial_user_info.html' %}
             </div>

            <div class="home_center" align="right">
                  {% include 'partial_user_info/partial_home_center.html' %}
            </div>

    {% elif user.is_authenticated %}
            <h2>Hello {{ user.username }}</h2>

        <div align="right">
            <form class="form-inline my-2 my-lg-0" action="{% url 'DMS:search_files' user.pk %}" autocomplete="off">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="searchMe">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

        <div class="topnav">
            <p> <a href='#'> Dashboard </a> </p>
            <p> <a href="{%url 'DMS:dashboard'%}" > Document Management </a></p>
            <p> <a href="{% url 'DMSaccount:user_profile'%} "> My Account </a> </p>
        </div>

             <div align="left">
                 {% include 'partial_user_info/partial_user_info.html' %}
             </div>

            <div class="home_center" align="right">
                  {% include 'partial_user_info/partial_home_center.html' %}
            </div>



    {% else %}
              <p> <b>Document Management Systems (DMS)</b> are designed to organize business files and records digitally,
                whether they started out in paper form or were generated by software applications. Paper files are first
                converted to electronic format by scanning. This provides a more compact means of storage, universal
                access for retrieval, and higher levels of data security and privacy.</p>

          <p> <strong>Essential Components for Electronic Document Management Systems</strong></p>

        <p>1) Import </p>
        <p>2) Storage </p>
        <p>3) Identity </p>
        <p>4) Export </p>
        <p>5) Security </p>
    {% endif %}

{% endblock %}

DMSapp/templates/invoice.html
{% extends 'header.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
{% if user.is_authenticated %}
<br/>
<div class="breadcrumb_dms">
        <nav>
            <ol class="breadcrumb breadcrumb_lbl">
                <li class="breadcrumb-item"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a></li>
				<li class="breadcrumb-item"><a href="{%url 'DMS:document_upload' %}"> Upload Documents </a></li>

                <li class="breadcrumb-item active">{% trans 'Invoice' %}</li>
            </ol>
        </nav>
    </div>  

<form method="post" enctype="multipart/form-data" autocomplete="off">

<div class="col-6 mx-auto">
    <div class="card card.bg-success.text-white">
      <div class="card-header text-center bg-primary text-white">Upload Invoice</div>
      <div class="card-body">
<form method="post" enctype="multipart/form-data" autocomplete="off">

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}


    {% csrf_token %}
      <!-- {{ form | crispy }} -->

      {% for field in form %}
      <span>{{ field.label_tag }} {% if field.field.required %} * {% endif %}</span>
      <span>{{ field }}  </span><br>
      {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
      {% endfor %}
      {% endfor %}
      <canvas id="imageCanvas" width="20" height="20" style="margin-left:100px;"></canvas><br>
     <div class="text-center"><button type="submit" class="btn btn-primary" id="bb">Upload</button>
    <button class="btn btn-primary" type="reset">Cancel</button></div>
       </div>
      </div>
</div>
  </form>

{% else %}
  <h2>You are not logged in.Please login</h2>
{% endif %}
{% endblock %}

DMSapp/templates/reports_list.html
{% extends 'header.html' %}
{% load i18n %}
{% load staticfiles %}
{% block body_block %}
<title> Reports List </title>
<br/>
    <p class="breadcrumb breadcrumb_lbl"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a>/{% trans 'Report List' %}</p>

        <p class="breadcrumb accord"><a href="{% url 'WorkflowManagement:workflow_reports' %}">{% trans 'Workflow Report' %}</a></p>
        <p class="breadcrumb accord"><a href="{% url 'DMS:reports' %}">{% trans 'Personal Data Report' %}</a></p>
{% endblock %}