DMSapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [

	path('show_delete_popup/<int:file_id>/', views.show_delete_popup, name='show_delete_popup'),
    path('download/file/<int:id>/<type>/', views.download_protection, name='download'),
    url('fileupload/bulk_upload', views.bulk_upload, name='bulk_upload'),
    url(r'^$', views.home, name='home'),
    url(r'^fileupload/', views.fileupload, name='fileupload'),
    path('delete_archive_files/<int:id>/<type>/', views.delete_archive_files, name='delete_archive_files'),
    path('dashboard/', views.dashboard_view, name='dashboard'),

    path('user_files/', views.user_files, name='user_files'),
    url(r'document_upload', views.document_upload, name='document_upload'),

    path('delete_files/<int:id>/<type>/', views.delete_files_files, name='delete_files_files'),
	
	#user files
    path('root_files/<int:pk>/<type>/<username>', views.root_files, name='root_files'),
    path('user_files/<int:id>/<type>', views.user_files, name='user_files'),
    path('user_files/favorite/<int:file_id>', views.is_favorite, name='is_favorite'),
    path('starred_documents', views.starred_docs, name='starred_documents'),
    path('download/requested_file/<int:id>', views.download_history, name='download_file_request'),
    url(r'downloaded_files', views.download_files, name='downloaded_files'),
    path('total-document', views.total_document, name='total_document'),
    url(r'^send_to_share', views.send_to_share, name='send_to_share'),
    path('approval_sent_for_share/<int:id>', views.send_to_share, name='share_document'),

    path('approval_for_sharing/<int:id>', views.for_approval, name='for_approval'),
    path('all_files_for_sharing/', views.files_for_approval, name='files_for_approval'),
    path('all_files_for_sharing/<int:id>', views.files_for_approval, name='files_for_approval'),
    path('shared_documents/', views.shared_document, name='shared_document'),
    path('all_shared_documents', views.shared_by_all, name='all_shared_document'),
    path('stop_sharing/<int:id>/', views.stop_sharing, name='stop_sharing'),

    path('searchresults/<int:pk>/', views.search_files, name='search_files'),
    path('meta_search/', views.meta_search, name='meta_search'),
    path('document_view/<int:file_id>', views.document_protection, name='protecting_doc'),
    path('archive_files/', views.archive_files, name='archive_files'),
    url(r'access_history_table', views.access_history_table, name='access_history_table'),

    path('share_document_to_user/<int:file_id>', views.share_document_to_user, name='share_document_to_user'),
    path('shared_by_other', views.shared_by_other, name='shared_by_other'),
    path('notifications', views.notification_of_files, name='notification_files'),

    path('reports', views.reports, name='reports'),
    path('reports/other_users_info', views.other_users_info, name='other_users_info'),
    path('reports/reports_of_user/<int:user_id>', views.reports_of_user, name='reports_of_user'),

    path('notifications/notification_request', views.share_notification_request, name='share_notification_request'),
    path('notification/mark_read/<int:id>', views.mark_read, name='mark_read'),

    #account
    path('approval_form_for_account_opening/<int:task_id>/', views.approval_form_for_account_opening,
         name='approval_form_for_account_opening'),

    #Notes
    path('notification/notes', views.notes, name='notes'),
    path('notification/notes/<note>', views.notes, name='notes'),
    path('discussions/', views.discussions, name='discussions'),
    path('scan_document/', views.scan_document, name='scan_document'),


    url('bulk_upload_for_files', views.bulk_upload_for_files, name='bulk_upload_for_files'),

    #Encryption
    path('encrypt_document/<int:file_id>', views.encrypt_document, name='encrypt_document'),
    path('documents/encryption', views.encryption, name='encryption'),

    #Share Externally
    path('share_document_to_user/externally/<int:file_id>', views.share_files_externally, name='share_files_externally'),
    url(r'^document_shared_externally/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.document_shared_externally, name='document_shared_externally'),
    path('download_externally/requested_file/<int:id>', views.download_externally, name='download_externally'),

        #Account open
    path('workflow_management/', views.workflow_management, name='workflow_management'),
    path('account_opening_approval', views.account_opening_approval, name='account_opening_approval'),
    url(r'account_open', views.account_open, name='account_open'),
    path('notification/mark_read_account/<int:id>', views.mark_read_account, name='mark_read_account'),
    url(r'workflow_management/approved_forms', views.approved_forms, name='approved_forms_for_AO'),
    url(r'workflow_management/rejected_forms', views.rejected_forms, name='rejected_forms_for_AO'),

    path('delete_notification_for_workflow/<int:notif_id>', views.delete_notification_for_workflow, name='delete_notification_for_workflow'),
    path('validate_filename/', views.validate_filename, name='validate_filename'),
    path('replace_file/', views.replace_file, name='replace_file'),
    path('restore_document/<int:file_id>', views.restore_document, name='restore_document'),
    path('check_valid_password/', views.check_valid_password, name='check_valid_password'),
    path('delete_sticky_notes/<int:note_id>', views.delete_sticky_notes, name='delete_sticky_notes'),
    path('edit_sticky_notes/<int:note_id>', views.edit_sticky_notes, name='edit_sticky_notes'),
    path('check_protection/<int:id>/<url_sub>/', views.check_protection, name='check_protection'),
    
    path('ask_replace_file_password/<int:file_id>/', views.ask_replace_file_password, name='ask_replace_file_password'),
    path('share_locked_file/<int:file_id>/', views.share_locked_file, name='share_locked_file'),
    
    path('table_request_form', views.table_request_form, name='table_request_form'),
    path('theme_management_selection', views.theme_management_selection, name='theme_management_selection'),
	
	#data to pdf
	path('data_to_excel', views.data_to_excel, name='data_to_excel'),
    path('data_to_pdf', views.data_to_pdf, name='data_to_pdf'),
    path('report_list', views.report_list, name='report_list'),

]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DMSproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from DMSapp import views as DMSapp_views
from DMSContact import views as DMSContact_views
from DMSpages import views as DMSpages_views
from DMSaccount import views as DMSaccount_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ajax_select import urls as ajax_select_urls

admin.site.site_header = "DMS Admin"
admin.site.site_title = "DMS Admin Portal"
admin.site.index_title = "Welcome to Document Management System!!"

urlpatterns = [
    # path('home/<DMS>', DMSapp_views.home, name='home'),
    url(r'^$', DMSapp_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('admin1', DMSaccount_views.admin, name='admin'),
    path('home/<DMS>', DMSapp_views.home, name='home'),
    path('home/', DMSapp_views.home, name='home'),
    url(r'^ajax_select/', include(ajax_select_urls)),
    path('signup/', DMSaccount_views.signup, name='signup'),
    path('login/', DMSaccount_views.login1, name='user_login'),
    path('password/', DMSaccount_views.change_password, name='change_password'),
    path('user_files/<int:id>/', DMSapp_views.user_files, name='user_files'),
    url(r'^', include(('DMSapp.urls', 'DMSapp'), namespace='DMS')),
    url(r'^', include(('DMSpages.urls', 'DMSpages'), namespace='DMSpages')),
    url(r'^', include(('DMSaccount.urls', 'DMSaccount'), namespace='DMSaccount')),
    url(r'^', include(('DMSloader.urls', 'DMSloader'), namespace='DMSloader')),
    url(r'^', include(('twofactor.urls', 'twofactor'), namespace='two_factor')),
    url(r'^', include(('WorkflowManagement.urls', 'WorkflowManagement'), namespace='WorkflowManagement')),

    path('root_files/<int:pk>/', DMSapp_views.root_files, name='root_files'),

    # for OTP
    path('sendOTP/<id>/', DMSaccount_views.send_otp, name='send_otp'),
    path('resendOTP/<id>/<mobile_no>/', DMSaccount_views.resend_otp, name='resendOTP'),
    path('enterOTP/<id>/<mobile_no>/', DMSaccount_views.enter_otp, name='enterOTP'),
    path('verifyOTP/<id>/<mobile_no>/', DMSaccount_views.verify_otp, name='verifyOTP'),
    # path('detectorAndTrainer/(?P<id>\d+)/',DMSaccount_views.detectorAndTrainer, name='detectorAndTrainer'),
    path('contact/', DMSContact_views.contact, name='contact'),
    path('load_pages/', DMSpages_views.home, name='load_pages'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += [url(r'^captcha/', include('captcha.urls')), ]


urlpatterns += [url(r'^ckeditor/', include('ckeditor_uploader.urls')), ]

WorkflowManagement/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [

    path('workflow_form_selection', views.workflow_form_selection, name='workflow_form_selection'),
    path('workflow_management_selection/<int:queryset_id>', views.workflow_management_selection, name='workflow_management_selection'),
    path('workflow_management_form_view/<int:queryset_id>', views.workflow_form_view, name='workflow_form_view'),
    path('removeField/<int:queryset_id>/<label>', views.remove_field, name='removeField'),
    path('validate_label_name_workflow/<int:queryset_id>', views.validate_label, name='validate_label'),
    path('validate_mobile_number_workflow/', views.checkmobile, name='validate_mobile_number_workflow'),
    path('validate_pan_number_workflow/', views.validate_pan_number, name='validate_pan_number'),
    path('validate_aadhar_number/', views.validate_aadhar_number, name='validate_aadhar_number'),
    path('validateEmail/', views.validateEmail, name='validateEmail'),
    path('confirm_workflow/<int:queryset_id>', views.confirm_workflow, name='confirm_workflow'),
    path('toggle_button/<int:wf_id>', views.toggle_button, name='toggle_button'),
    path('validateOnlyAlphabets/', views.validateOnlyAlphabets, name='validateOnlyAlphabets'),
    path('workflow_management', views.workflow_management, name='workflow_management'),
    path('delete_workflow/<int:id>', views.delete_workflow, name='delete_workflow'),
    path('validateAlphaNumeric/', views.validateAlphaNumeric, name='validateAlphaNumeric'),
    path('workflow_selection_for_department', views.workflow_selection_for_department, name='workflow_selection_for_department'),
    path('fill_workflow_form/<int:queryset_id>', views.fill_workflow_form, name='fill_workflow_form'),
    path('all_wf_forms/<int:queryset_id>/<status>', views.all_wf_forms, name='all_wf_forms'),
    path('all_wf_forms/<int:queryset_id>/<status>/<int:read>', views.all_wf_forms, name='all_wf_forms'),
    path('all_workflow_for_maker', views.all_workflow_for_maker, name='all_workflow_for_maker'),
    path('all_user_forms_workflow/<int:forms_pk>', views.all_user_forms_workflow, name='all_user_forms_workflow'),
    path('all_user_forms_workflow/<int:forms_pk>/<int:read>', views.all_user_forms_workflow, name='all_user_forms_workflow'),
    path('edit_workflow_maker/<int:user_data_pk>', views.edit_workflow_maker, name='edit_workflow_maker'),
    path('submit_to_checker/<int:user_data_pk>', views.submit_to_checker, name='submit_to_checker'),
    path('all_workflow_for_checker', views.all_workflow_for_checker, name='all_workflow_for_checker'),
    path('all_wf_for_approval/<int:wf_id>', views.all_wf_for_approval, name='all_wf_for_approval'),
    path('customer_data_for_approval/<int:data_id>', views.customer_data_for_approval, name='customer_data_for_approval'),
    path('customer_data_for_approval/<int:data_id>/<int:read>', views.customer_data_for_approval, name='customer_data_for_approval'),
    path('checker_for_approval/<int:data_id>', views.checker_for_approval, name='checker_for_approval'),

    path('all_rejected_forms/<int:form_id>', views.all_rejected_forms, name='all_rejected_forms'),
    path('all_rejected_forms/<int:form_id>/<int:read>', views.all_rejected_forms, name='all_rejected_forms'),
    path('delete_form/<int:form_id>', views.delete_form, name='delete_form'),

    url('image_ocr', views.image_ocr ,name='image_ocr'),

    path('scan_documents', views.scan_documents_sanelib, name='scan_documents_sanelib'),
    path('document_scan_parameter', views.document_scan_parameter, name='document_scan_parameter'),

    path('scanned_images', views.scanned_images, name='scanned_images'),
    path('scanned_user_data', views.scanned_user_data, name='scanned_user_data'),
    path('submit_tag_option', views.submit_tag_option, name='submit_tag_option'),
    path('crop_popup/', views.crop_popup, name='crop_popup'),
    path('submit_cropped_image', views.submit_cropped_image, name='submit_cropped_image'),
    path('save_rotated_image', views.save_rotated_image, name='save_rotated_image'),

    path('ajax_scanned_document', views.ajax_scanned_document, name='ajax_scanned_document'),
    path('ajax_login_call', views.ajax_login_call, name='ajax_login_call'),

    # New Changes in Workflow

    #path('workflowProcess', views.workflowProcess, name='workflowProcess'),

    path('workflow_process/<int:id>',views.workflow_process,name='workflow_process'),
    path('workflow_process/workflowLogin', views.workflowLogin, name='workflowLogin'),
    path("workflowDocsLogin", views.workflowDocsLogin, name='workflowDocsLogin'),
    path('fetch_data_from_finacle', views.fetch_data_from_finacle, name='fetch_data_from_finacle'),
    path('confirm_finacle_entry/<int:user_data_pk>', views.confirm_finacle_entry, name='confirm_finacle_entry'),

    path('workflow_docs', views.workflow_docs, name='workflow_docs'),
    path('workflow_docs_search', views.workflow_docs_search, name='workflow_docs_search'),

    path('download_workflow_docs/<int:value>/<str_value>', views.download_workflow_docs, name="download_workflow_docs"),
    path('download_workflow_docs/<int:value>', views.download_workflow_docs, name="download_workflow_docs"),
    path('confirm_workflow_docs', views.confirm_workflow_docs, name="confirm_workflow_docs"),

    path('del_workflow_docs/<int:value>/<str_value>', views.del_workflow_docs, name="del_workflow_docs"),
    path('del_workflow_docs/<int:value>', views.del_workflow_docs, name="del_workflow_docs"),

    path('view_mis_report', views.view_mis_report, name='view_mis_report'),
    path('save_image_workflow_process', views.save_image_workflow_process, name="save_image_workflow_process"),
    path('workflow_docs_for_version', views.workflow_docs_for_version, name='workflow_docs_for_version'),
    url(r'^download_version_file/(?P<path>.*)$', views.download_version_file, name='download_version_file'),


    path('ajax_call_for_files', views.ajax_call_for_files, name='ajax_call_for_files'),
    path('workflow_docs_list', views.workflow_docs_list, name="workflow_docs_list"),
    path('view_approved_document/<doc>/<doc_id>', views.view_approved_document, name="view_approved_document"),
    
    path('extract_account_numner_nodata/<value>', views.extract_account_numner_nodata, name='extract_account_numner_nodata'),
    path('delete_workflow_scanned_data/<int:value>', views.delete_workflow_scanned_data, name='delete_workflow_scanned_data'),

    path('download_workflow_document_for_ckyc/', views.download_workflow_document_for_ckyc, name='download_workflow_document_for_ckyc'),
    path('workflow_reports', views.workflow_reports, name='workflow_reports'),
]


urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WorkflowManagement/templates/workflow_files/rejected_forms.html
{% extends 'header.html' %}
{% block body_block %}
{% load i18n %}
<title> {% block title %} Workflow Process {% endblock %}</title> 
<style>
  label
  {
  font-weight:bold
  }
</style>
<br/>
<br/>
  
<div class="breadcrumb_dms">
        <nav>
            <ol class="breadcrumb breadcrumb_lbl">
                <li class="breadcrumb-item"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item">
                    <a href="{% url 'WorkflowManagement:workflow_management' %}">{% trans 'Workflow Management' %}</a>
                </li>
				<li class="breadcrumb-item"><a href="{% url 'WorkflowManagement:all_workflow_for_maker' %}">{% trans 'Maker' %}</a> </li>
				<li class="breadcrumb-item"><a href="{%url 'WorkflowManagement:all_wf_forms' data.workflow_id.id 'Rejected' %}">{% trans 'Forms To Check' %}</a></li>
                <li class="breadcrumb-item active">{% trans 'Rejected Form' %}</li>
            </ol>
        </nav>
    </div>

<div class="col-6 mx-auto">
    <div class="card card.bg-success.text-white">
      <div class="card-header text-center bg-primary text-white"><strong>{% trans 'Rejected Form' %}</strong>
      <span style="float:right">
        <a href="{% url 'WorkflowManagement:edit_workflow_maker' data.pk %}"><i title="Edit Record" class="fa fa-edit fa-lg"></i></a>
       <a data-url="{% url 'WorkflowManagement:delete_form' data.pk %}" class="delete_wf"><i title="Delete Record" class="fa fa-trash fa-lg"></i></a>
      </span>
      </div>
      <div class="card-body">
          <table style="width:100%" cellpadding="4">
       {% for data in json_data %}
        {% for i,j in data.items  %}
      {% if '/media/Workflow_Management/' in j %} 
      <tr>
      <td>
        <label  class="col-xs-2 col-form-label">{{i}} : &nbsp;</label>
      </td>
     <td> 
    <div  class="col-sm-4"> 
   <img src="{{j}}" class="img-responsive border" alt="Image" width="100">
   </div>
    </td>    
    </tr> 
     {% elif '[' and ']' in j %}
    <tr>
    <td>   
       <label class="col-xs-2 col-form-label">{{i}} : &nbsp;</label>
    </td>
    <td>
    <div class="col-sm-10">
       <input type="text" class="form-control" value="{{j|slice:'1:-1'}}" READONLY/> 
    </div>
    </td>    
    </tr>
  {%else%}
      <tr>
         <td>
      <label class="col-xs-2  col-form-label">{{i}}:</label>
             </td>
         <td>
         <div class="col-sm-10">
                <input type="text" class="form-control" value="{{j}}" READONLY/>
             </div>
         </td>
        </tr>

 {% endif %}

    {% endfor %}
  {% endfor%}


        <tr>
  <td>
      <label class="col-xs-2 col-form-label">{% trans 'Status:' %} </label>
     </td>
          <td>
            <div class="col-sm-10">
                <input type="text" class="form-control" value="{{data.status}}" READONLY/>
             </div>
          </td>
        </tr>
        <tr>
          <td>
            <label class="col-xs-2 col-form-label">{% trans 'Remarks:' %}</label>
          </td>
          <td>
            <div class="col-sm-10">
                <input type="text" class="form-control" value="{{data.remarks}}" READONLY/>
             </div>
          </td>
        </tr>
          </table>

 </div>
    </div>
  </div>


<div class="modal fade" id="modal-book">
      <div class="modal-dialog">
        <div class="modal-content"></div>
      </div>
    </div>

<script>
    $('.delete_wf').on("click",function (){


         var btn = $(this);
         $.ajax({
           url: btn.attr("data-url"),
           type: 'get',
           dataType: 'json',
           beforeSend: function () {
             $("#modal-book").modal("show");


           },
           success: function (data) {
             $("#modal-book .modal-content").html(data.html_form);
           }
         });

      });
</script>

{% endblock %}

WorkflowManagement/templates/workflow_files/workflow_docs_search.html
{% extends 'header.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block body_block %}
{% load i18n %}
<title> {% block title %} Workflow Docs {% endblock %} </title> 
<head>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'table/css/jquery.dataTables.css' %}"/>
    <script src = "{% static 'table/js/jquery.dataTables.js' %}"></script>

</head>
<br/>

<div class="breadcrumb_dms">
        <nav>
            <ol class="breadcrumb breadcrumb_lbl kClass">
                <li class="breadcrumb-item"><a href="{% url 'DMS:home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item">
                    <a href="{% url 'WorkflowManagement:workflow_management' %}">{% trans 'Workflow Management' %}</a>
                </li>
				<li class="breadcrumb-item"><a href="{% url 'WorkflowManagement:workflow_docs' %}">{% trans 'Workflow Docs' %}</a></li>
                <li class="breadcrumb-item active">{% trans 'Search Document' %} </li>
            </ol>
        </nav>
    </div>

  <form id="personForm" method="post" data-cities-url="{% url 'WorkflowManagement:workflow_docs_search' %}" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="row">
    <div class="col-md-3">
        <input type="text" name="search_data"  maxlength="30" class="form-control form-control-sm" value="{{search_data}}" required="" placeholder="Enter Workflow No / Account Number" id="search_text" />
    </div>
          <div class="col-md-2">
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</div>
          <div class="col-md-7">
              <div class="p-2 float-right">
                   <input type="button" id="btn_delete" value="Delete" disabled class="btn btn-danger btn-sm">
              
            </div>
          </div>
      </div>
  </form>

<br/>
<div class="table-responsive">
         <table id = "case-table" class = "table table-bordered table-sm table-striped" style="white-space:nowrap">
            <thead class="table-info text-center">
                <tr>
                    <th>{% trans 'SrNo' %} </th>
                    <th>{% trans 'Document Name' %}</th>
                    <th>{% trans 'User' %}</th>
                </tr>
            </thead>
            <tbody id="tbody_id">
                {% if data_list %}
                    {% for da in data_list %}

                        <tr>
                                <td class="text-center"><input type="checkbox"/></td>
                                <td style="color:#007bff;"><a style="cursor:pointer" class="class_document" data-attr="{{da.account}}" data-attr-value="{{da.id}}">{{da.account}} </a> </td>
                                <td>None </td>
                        </tr>

                    {% endfor %}
                {% endif %}
            </tbody>
         </table>

    </div>

<script src="{% static 'javascript/workflow_docs_js.js' %}"></script>
<script>
    $(document).ready(function(){
        $.noConflict();
        $('#case-table').DataTable();
    });

    $('.class_document').on('click', function(e) {
        var docs = $(this).attr('data-attr');
        var wf_id = $(this).attr('data-attr-value');
        window.open("/workflow_docs_list?docs=" + docs + "&id="+wf_id,null,"height=680px, width=1350px,bottom=10, status=no, resizable=yes");

    });

	$('#btn_delete').on('click', function(e) {

            $("#tbody_id input[type=checkbox]:checked").each(function () {
                var row = $(this).closest("tr")[0];
                console.log(row.cells[1])

                message = $(row.cells[1]).find(".class_document").text();
                value = $(row.cells[1]).find(".class_document").attr('data-attr-value');

            });
            console.log("message", message, value)
            if (message != "") {
                    data_url = "delete_workflow_scanned_data/" + value;

                     $.getJSON(data_url, function(result) {
                    if (result){
                         alert('Deleted');
                     }
                    else {
                        alert("No Such Account")
                        window.location.reload(true);
                    }
                });

            }

            return false;
        });

      $('#tbody_id').on('change', 'input[type=checkbox]', function() {

                   $('#btn_delete').prop('disabled', false);

                if($('#tbody_id input:checked').length >= 2){
                    $('#btn_delete').prop('disabled', true);
                }

                if($('#tbody_id input:checked').length == 0){
                    $('#btn_delete').prop('disabled', true);
                }

        });


 </script>

{% endblock %}

WorkflowManagement/templates/workflow_files/workflow_names.html
{% load staticfiles %}
{% load i18n %}
{% if files %}
{% for i in files %}
     <tr>
        <td>{{ i.fields.srNo }}</td>
        <td>{{ i.fields.wf_name }}</td>
        <td> <label class="switch">
            <input data-cities-url="{% url 'WorkflowManagement:toggle_button' i.pk %}" type="checkbox"
                           data-target="{{i.pk}}"  class="togbtn" id="togBtn_{{i.pk}}" data-attr-value="{{ i.fields.status }}"
                            data-attr-value_foo="{{i.fields.wf_definition}}" {% if i.fields.status %} checked {%endif%}>
                <span id="{{i.pk}}"  class="{% if i.fields.status %} myclass slider xyz round_{{i.pk}} {% else %} slider abc round_{{i.pk}} {% endif %}"
                      data-count="{% if i.fields.status %} ON {% else %} OFF {% endif %}">
                </span>

            </label>
        </td>
         <td>
            <a data-url="{% url 'WorkflowManagement:delete_workflow' i.pk %}" title="Delete Record" class="btn btn-danger delete_wf wf_{{i.pk}} {% if i.fields.status %} disabled {% endif %}"><i class="fa fa-trash"></i></a>
         </td>
         <td>
		{% if  i.fields.status == False %}  <!--When it was blank then use '""'  -->
            <a href="{% url 'WorkflowManagement:workflow_management_selection' i.pk %}" title="Create Record" class="btn btn-warning"><i class="fa fa-edit"></i></a>

            {% else %}
            <a href="{% url 'WorkflowManagement:workflow_form_view' i.pk %}" title="Edit Record" class="btn btn-info"><i class="fa fa-edit"></i></a>
            {% endif %}
         </td> 
	 </tr>
    {% endfor %}
{% else %}
  <tr>
    <td colspan="6"><h1 id="no">{% trans 'No Records Found' %}</h1></td>
  </tr>


{% endif %}
<script>

    $('.delete_wf').on("click",function (){
         var btn = $(this);
         $.ajax({
           url: btn.attr("data-url"),
           type: 'get',
           dataType: 'json',
           beforeSend: function () {
             $("#modal-book").modal("show");


           },
           success: function (data) {
             $("#modal-book .modal-content").html(data.html_form);
           }
         });

      });
     
       $(".togbtn").on('change', function() {
     var check = $(this).attr('data-attr-value');
       var url = $(this).attr('data-cities-url');
       var id2  = $(this).attr('data-target');
       var id = $('.round_' + id2).attr('id');
       var wf_def = $(this).attr('data-attr-value_foo');
        if (wf_def){
            $.getJSON(url, function(result) {
                    if (result.success) {
                        $('.round_' + id2).attr('data-count', 'ON');
                        $('.round_' + id2).removeClass('abc');
                        $('.round_' + id2).addClass('xyz');
                        $('.wf_' + id2).addClass('disabled');
                        document.getElementById('togBtn_' + id2).checked = true;
                    }
                    else{
                        $('.round_' + id2).attr('data-count', 'OFF');
                        $('.round_' + id2).removeClass('xyz');
                        $('.round_' + id2).addClass('abc');
                        $('.wf_' + id2).removeClass('disabled');
                        console.log('togBtn_' + id2)
                        document.getElementById('togBtn_' + id2).checked = false;
                    }

                });
                return false;
         }
         else{
            console.log("dgfdh");
            $('.round_' + id2).addClass('disabled');
            $('.round_' + id2).attr('title', 'Form is not yet created');
         }
    });



</script>